//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKB_THCS
{
    using System;
    using System.Collections.Generic;
    
    public partial class LopHoc
    {
        public int IDLop { get; set; }
        public Nullable<int> IDGV { get; set; }
        public Nullable<int> IDPH { get; set; }
        public Nullable<int> Nam { get; set; }
        public Nullable<int> Khoi { get; set; }
        public string TenLop { get; set; }
        public Nullable<int> SiSo { get; set; }
        public Nullable<int> BuoiHoc { get; set; }
    
        public virtual GiaoVien GiaoVien { get; set; }
        public virtual PhongHoc PhongHoc { get; set; }
    }
}
