//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKB_THCS
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonHoc
    {
        public MonHoc()
        {
            this.GiaoViens = new HashSet<GiaoVien>();
        }
    
        public int IDMon { get; set; }
        public string Ten { get; set; }
        public Nullable<bool> Khoi6 { get; set; }
        public Nullable<bool> Khoi7 { get; set; }
        public Nullable<bool> Khoi8 { get; set; }
        public Nullable<bool> Khoi9 { get; set; }
        public Nullable<int> SoTietK6 { get; set; }
        public Nullable<int> SoTietK7 { get; set; }
        public Nullable<int> SoTietK8 { get; set; }
        public Nullable<int> SoTietK9 { get; set; }
        public Nullable<int> SoBuoiK6 { get; set; }
        public Nullable<int> SoBuoiK7 { get; set; }
        public Nullable<int> SoBuoiK8 { get; set; }
        public Nullable<int> SoBuoiK9 { get; set; }
        public Nullable<bool> Kep { get; set; }
        public Nullable<bool> Phu { get; set; }
    
        public virtual ICollection<GiaoVien> GiaoViens { get; set; }
    }
}
